name: Deploy PHP Website

on:
  push:
    branches:
      - main # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        env:
          SSH_AUTH_SOCK: ${{ steps.ssh-agent.outputs.ssh-auth-sock }}

      - name: Copy Files to Server
        run: scp -r ./path/to/your/php/project/* lexusvp.github.io/Ellipsis/path/to/destination/folder/
        
      - name: SSH into Server and Deploy
        run: |
          ssh lexusvp.github.io/Ellipsis << 'EOF'
            cd /path/to/destination/folder/
            composer install # If you use Composer for dependencies
            php artisan migrate # If you use Laravel, for example
            # Additional deployment steps or commands
          EOF
